version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: events/eventcatalog
    build:
      context: .\EventsCatalogAPI
      dockerfile: Dockerfile
    environment: 
      ExternalBaseUrl: http://localhost:7015
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventCatalogDb;User Id=sa;Password=ProductApi123;Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
    ports:
      - 7015:80
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
  
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123
    ports:
      - "1899:1433"
    container_name: eventscatalogsqlserver
    networks:
      - backend

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://eventcatalog
      IdentityUrl: http://172.25.144.1:7600
      CallBackUrl: http://localhost:7300
    ports:
      - "7300:80"
    container_name: webeventshop
    networks:
      - frontend
    depends_on:
      - eventcatalog

  
  
      