
version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: events/catalogapi
    
    build:
      context: ./EventsCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=CatalogDb;User Id=sa;Password=EventsApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      ExternalBaseUrl: http://localhost:7015
    ports:
      - "7015:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    image: jewels/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:8500
    ports:
      - "7800:80"
    container_name: eventstokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver  

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://eventcatalog
      IdentityUrl: http://192.168.1.131:7800
      CallbackUrl: http://localhost:8500
    ports:
      - "8500:80"
    container_name: eventwebshop
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - tokenserver

  
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventsApi123(!)
    ports:
      - "1558:1433"
    container_name: eventscatalogsqlserver
    networks:
      - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventsApi123(!)
    ports:
      - "1559:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

