
version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalog:
    image: events/catalogapi
    
    build:
      dockerfile: Dockerfile
    environment: 
    ports:
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
  
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
    ports:
    container_name: eventscatalogsqlserver
    networks:
      - backend

