version: '3.4'

networks:
  frontend:
  backend:


services:
  eventcatalog:
    image: events/catalogapi
    build:
      context: .\EventsCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false"
      ExternalBaseUrl: http://localhost:8000
    ports:
      - "8000:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on: 
      - mssqlserver

  webmvc:
   image : events/webmvc
   build:
     context: .\WebMvc
     dockerfile: Dockerfile
   environment : 
    CatalogUrl: http://eventcatalog
   ports:
     - "8500:80"
   container_name: webeventshop
   networks:
     - frontend 
   depends_on:
     - eventcatalog
    
    
  mssqlserver:
   image: "mcr.microsoft.com/mssql/server:latest"
   environment :
     ACCEPT_EULA: Y
     MSSQL_SA_PASSWORD: ProductApi123(!)
   ports:
     - "1449:1433" 
   container_name: eventscatalogsqlserver
   networks:
     - backend